---
apiVersion: v1
kind: Namespace
metadata:
  name: conjur-ee

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-enterprise
  namespace: conjur-ee
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur
  template:
    metadata:
      labels:
        app: conjur
    spec:
      containers:
      - name: conjur-master
        imagePullPolicy: IfNotPresent
        image: registry2.itci.conjur.net/conjur-appliance:4.9.16.0
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 636
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 5433
            protocol: TCP
      - name: conjur-cli
        imagePullPolicy: IfNotPresent
        image: captainfluffytoes/docker_conjur_cli
      imagePullSecrets:
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  namespace: conjur-ee
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: conjur
  type: NodePort