---
apiVersion: v1
kind: Namespace
metadata:
  name: cyberark-conjur-enterprise

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: cyberark-conjur-enterprise
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-node
      role: master
  template:
    metadata:
      labels:
        app: conjur-node
        role: master
    spec:
      containers:
      - name: master
        imagePullPolicy: Always
        image: registry2.itci.conjur.net/conjur-appliance:4.9.18.0
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 636
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 5433
            protocol: TCP
      imagePullSecrets:
      - name: regcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  namespace: cyberark-conjur-enterprise
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-node
      role: cli
  template:
    metadata:
      labels:
        app: conjur-node
        role: cli
    spec:
      containers:
      - name: cli
        imagePullPolicy: Always
        image: captainfluffytoes/docker_conjur_cli
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: standbys
  namespace: cyberark-conjur-enterprise
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-node
      role: standby
  template:
    metadata:
      labels:
        app: conjur-node
        role: standby
    spec:
      containers:
      - name: standby
        imagePullPolicy: Always
        image: registry2.itci.conjur.net/conjur-appliance:4.9.18.0
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 636
            protocol: TCP            
          - containerPort: 5432
            protocol: TCP  
          - containerPort: 5433
            protocol: TCP
      imagePullSecrets:
      - name: regcred
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers
  namespace: cyberark-conjur-enterprise
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-node
      role: follower
  template:
    metadata:
      labels:
        app: conjur-node
        role: follower
    spec:
      containers:
      - name: follower
        imagePullPolicy: Always
        image: registry2.itci.conjur.net/conjur-appliance:4.9.18.0
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 636
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 5433
            protocol: TCP
      imagePullSecrets:
      - name: regcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authnk8s
  namespace: cyberark-conjur-enterprise
  labels:
    app: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-node
      role: authnk8s
  template:
    metadata:
      labels:
        app: conjur-node
        role: authnk8s
    spec:
      containers:
      - name: follower
        imagePullPolicy: Always
        image: registry2.itci.conjur.net/conjur-appliance:4.9.18.0
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/prod
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 636
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 5433
            protocol: TCP
      imagePullSecrets:
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  namespace: cyberark-conjur-enterprise
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    role: master
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: conjur-standby
  namespace: cyberark-conjur-enterprise
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    role: standby
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  namespace: cyberark-conjur-enterprise
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    app: conjur-follower
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-authnk8s
  namespace: cyberark-conjur-enterprise
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    role: authnk8s
  type: NodePort