---
apiVersion: v1
kind: Namespace
metadata:
  name: web_app
  
---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  namespace: web_app
  labels:
    app:  authnk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authnk8s
      role: app
  template:
    metadata:
      labels:
        app: authnk8s
        role: app
    spec:
      serviceAccountName: test-app
      containers:
      - name:
        image:
        imagePullePolicy: Always
        env:
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: cyberark/conjur-openshift-authenticator
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api
          - name: CONJUR_AUTHN_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api/authn-k8s/prod
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_AUTHN_LOGIN
            value: web_app/service_account/test-app
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
      
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: web_app
spec:
  ports:
  - protocal: tcp
    port: 80
  selector:
    role: app
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app