---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app
  namespace: k8s-app
  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: test-app-conjur-authenticator-role-binding
  namespace: k8s-app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cyberark-conjur-enterprise
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: test-app
      containers:
      - name: test-app
        image: captainfluffytoes/docker_k8s_test_app2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: k8s-app-ssl
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - name: authenticator
        image: cyberark/conjur-kubernetes-authenticator
        imagePullPolicy: Always
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api
          - name: CONJUR_AUTHN_URL
            value: https://conjur-authnk8s.cyberark-conjur-enterprise.svc.cluster.local/api/authn-k8s/prod
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_AUTHN_LOGIN
            value: k8s-app/*/*
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: k8s-app-ssl
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: conjurregcred
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
            
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: k8s-app
  labels:
    app: test-app
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: test-app
  type: NodePort